### PR TITLE
Fix usage of set_len to avoid UB

### LINKED ISSUE #133: Clean up `set_len`
There's `set_len` used in the code before actually initializing the `Vec`. This is not strictly UB because the data is not read and only raw pointer is used, however it's not idiomatic, and swapping the lines wouldn't break anything. There's also extra allocation in the method.

### PR DESCRIPTION
**Pull request by bigspider**
The interface of Serializable::serialize was inherently unsafe as it was expected to be called with uninitialized buffers, but this was not reflected in the type of the `buf` argument.

The procedural macros and UX code in app-sdk are updated accordingly.

Closes: #133

### CODE REVIEW

File: app-sdk/build_utils/mod.rs [hunk 1]
```diff
@@ -74,18 +74,17 @@ pub fn make_page_maker(file: &mut File, parts: &[SerializedPart], fn_name: &str)
...
-    {}.serialize(&mut serialized, &mut cur);",
+    {}.serialize(slice, &mut cur);",
                     arg_name, arg_name
                 )
                 .expect("Could not write");
             }
         }
 
-        writeln!(file, "    show_page_raw(&serialized);").expect("Could not write");
+        writeln!(file, "    let bytes = unsafe {{ core::mem::transmute::<&[MaybeUninit<u8>], &[u8]>(&serialized[0..total_len]) }};").expect("Could not write");
```
[the remark this answers is not in the document]
Comment (bigspider) [reply app-sdk/build_utils/mod.rs:88]: Unstable feature. Adding a comment.

File: common/src/ux/codec.rs [hunk 2]
```diff
@@ -1,20 +1,23 @@
 use alloc::{string::String, vec::Vec};
-use core::convert::TryInto;
+use core::{convert::TryInto, mem::MaybeUninit};
 
 pub trait Serializable {
     fn get_serialized_length(&self) -> usize;
-    fn serialize(&self, buf: &mut [u8], pos: &mut usize);
+    fn serialize(&self, buf: &mut [MaybeUninit<u8>], pos: &mut usize);
```
Comment (Kixunil) [inline common/src/ux/codec.rs:16]: Why does this trait take `pos` rather than just `buf` (possibly as `&mut &mut [MaybeUninit<u8>]`) and let the caller adjust the position only if needed? I think it should remove a bunch of checks.

File: common/src/ux/codec.rs [hunk 3]
```diff
@@ -1,20 +1,23 @@
 use alloc::{string::String, vec::Vec};
-use core::convert::TryInto;
+use core::{convert::TryInto, mem::MaybeUninit};
 
 pub trait Serializable {
```
Comment (Kixunil) [inline common/src/ux/codec.rs:4]: Unfortunately, taking in `MaybeUninit` suggests that the calling code can rely on the buffer being initialized but in that case the trait needs to be `unsafe`. But this is obviously annoying and harder to review. I guess a better approach would be:

```rust
pub use buffer::Buffer;
// mod needed to decrease the review surface
mod buffer {
    pub struct Buffer<'a> {
        slice: &'a mut [MaybeUninit<u8>],
         // invariant: written <= slice.len()
        written: usize,
    }

    impl<'a> Buffer<'a> {
        pub fn new(buf: &'a mut [MaybeUninit<u8>]) -> Self { Self { slice: buf, written: 0 } }
        pub fn written(&self) -> &[u8] { unsafe { self.slice.get_unchecked(..self.written) } }
        pub fn spare(&mut self) -> &[MaybeUninit] { unsafe { self.slice.get_unchecked(self.written..) } }
        pub unsafe fn assume_written(&mut self, len: usize) {
            debug_assert!(self.written + len <= self.slice.len());
            self.written += len;
        }
    }
}

impl Buffer<'_> {
    pub fn write(&mut self, data: &[u8]) {
        assert!(data.len() <= self.spare().len());
        self.spare()[..data.len()].copy_from_slice(unsafe { &*(data as *const _ as *const [MaybeUninit<u8>]) });
        unsafe { self.assume_written(data.len()) }
    }
}

pub trait Serialize {
    // ...
    fn serialize(&self, buf: &mut Buffer<'_>);
}
```

Then the implementors can mostly use the `write` method to write (while still being able to access the raw pointer) and the callers can use the `written` method to safely obtain the written data.

File: app-sdk/build_utils/mod.rs [hunk 4]
```diff
@@ -83,7 +83,10 @@ pub fn make_page_maker(file: &mut File, parts: &[SerializedPart], fn_name: &str)
             }
         }
 
+        // Note: We could use core::mem::MaybeUninit::slice_assume_init_ref, but it requires the unstable feature maybe_uninit_slice
+        // https://github.com/rust-lang/rust/issues/63569
         writeln!(file, "    let bytes = unsafe {{ core::mem::transmute::<&[MaybeUninit<u8>], &[u8]>(&serialized[0..total_len]) }};").expect("Could not write");
```
Comment (Kixunil) [inline app-sdk/build_utils/mod.rs:88]: Perhaps you could just make your own function.

**Comment by Kixunil** [comment]
This PR is not doing what I had in mind but seems useful anyway.

File: common/src/ux/codec.rs (hunk 3 above)
Comment (bigspider) [reply common/src/ux/codec.rs:4]: I kinda assumed that `MaybeUninit` would explicitly imply that you have to "make sure things are initialized before casting", but indeed I suppose if `serialize` were safe, I wouldn't need an extra safety contract in the documentation.

Opened #144 to track this.

> in that case the trait needs to be `unsafe`.

Wouldn't marking `serialize()` `unsafe` be enough, instead of the whole trait?

Comment (Kixunil) [reply common/src/ux/codec.rs:4]: Well, the issue is that the trait method needs to document what exact part of the slice is or isn't initialized because that's not obvious from the signature.

> Wouldn't marking `serialize()` `unsafe` be enough, instead of the whole trait?

No, because the contract is reversed here: it's safe to call the `serialize` function (it will not cause UB in any case) but it's not safe to *implement* it because wrong implementation will cause problems down the line.

(To be clear, the `Buffer` idea doesn't require `unsafe` trait because it completely manages the unsafety within itself on both sides.)
